[build]
  publish = "dist"  # Adjust this to your build output directory if different
  command = "npm run dev"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
